### PR TITLE
Re-add execute code (eden)

### LINKED ISSUE #165: Missing Execute Code (3den) In default modules PVP and COOP

### PR DESCRIPTION
**Pull request by Seb105**
Closes #165

### CODE REVIEW

**Comment by JamesTheClarke** [comment]
Added a small commit to fix #167

**Comment by JamesTheClarke** [comment]
Added two more commits regarding Default Modules, for changelog see individual commits:

https://github.com/CntoDev/compositions/pull/166/commits/97988a791ae3c29d333e157d283714acf06b7fcd
https://github.com/CntoDev/compositions/pull/166/commits/8954ed526486ffa3e3dc289e1e380b4b352244e6

**Comment by freghar** [comment]
If you want to leave a comment in place of the "Execute Code (Eden)" module instead of a static comment that's always present (and may be more easily missed), put this at the bottom of the executed code:
```sqf
params ["_module"];
do3DENAction "CreateComment"; 
private _comments = all3DENEntities select 7; 
private _3den_id = _comments select (count _comments - 1);
set3DENAttributes [ 
    [[_3den_id], "Name", "Something was here"], 
    [[_3den_id], "Description", format ["It was deleted when you placed it. Fix it.%1%1See wiki link TODO here.", toString[10]]], 
    [[_3den_id], "position", getPosASL _module]
]; 
```
(Adjust `Name` to be the subject and `Description` to be the description, %1 representing a line break (new line.))

Then try it out on some hilly terrain (I for got to try that). If it creates the comment high in the sky, change `getPosASL` to `getPosATL` and that should fix it.

**Review by JamesTheClarke — APPROVED** [review]
I've created a new issue to cover @freghar 's latest post in future updates.

**Review by baegel49 — APPROVED** [review]
it works

**Pull request merged**
