### PR TITLE
Standard factions 1.14.2

### LINKED ISSUE #77: Add Mortar Supply Crate to Compositions
Create a new Supply Crate containing mortar ammo (two bags), a set of map tools and a set of range-charts.

Relevant thread: https://www.carpenoctem.co/forums/m/26081621/viewthread/33152541-add-both-mortar-backpacks-to-standard-resupply

### LINKED ISSUE #82: Suggestion: Give Platoon leader a helmet
Platoon leaders should have a helmet, officers in modern militaries have helmets the same as everyone else.

### LINKED ISSUE #83: Suggestion: Give Engineers more ammo
Engineers only have 4 mags, they have loads of spare space in their backpacks and vests too. 
Rifleman first is a general principle and they cannot function as riflemen with this issue.

### LINKED ISSUE #86: DMT Marksman NVG Scope
The current TFN NVG scope carried by the marksman does not have a reticle or any means on aiming. I suggest the following scope is used instead AN/PVQ-31A (ARD/Lens Cover).

### LINKED ISSUE #94: Russian Army Sniper has Spotter class
Not a massive issue but the other factions are correct.

### LINKED ISSUE #95: Change the location of LR Radio to backpack
During the mission SL can often go unconscious which can last up to several minutes, depending on the severity of the wound. If a PLT is not right next to the downed SL it can be a while for him to find out what is happening because the next in command of the Squad is unable to retrieve the radio from the uniform of the downed person, unless the person is dead. 

I'm suggesting to change the location of the LR Radio from the uniform to the backpack for all members of the platoon that are in possesion of the LR so in case of the leader going down, next one in the chain of command can immediately retrieve it and inform the PLT lead.

### LINKED ISSUE #106: Remove NiArms G36 and MG3 assets from TFN
Due to adopting BW mod and subsequently removing duplicate NiArms mods the TFN faction will need to be adapted to exclude any NiArms G36 or MG3 assets.

https://www.carpenoctem.co/forums/m/26081621/viewthread/33263020-bw-modrepo-clean-up

### LINKED ISSUE #107: 1x epinephrine for each soldier
According to the July Monthly Meeting, it was decided to add 1x epi to each playable class. This change has to be implemented across all four standard factions and will need to be checked for custom factions going forward.

https://docs.google.com/document/d/1Lo6ssP8tul8LLI_iXvHhAnAQ2Xm6CpKbY3I7-2VekwU/edit#heading=h.8xxw6ujw21gl

### LINKED ISSUE #110: Potential Bug: ACRE2 Channel Presets
Today I joined in a TFN Bravo Team and noticed that my default radio channel was set to 1 instead of 2.

We may need to double-check if the A3AA update broke the default channels.

### LINKED ISSUE #112: RU and US Army Platoon Section: give uniform helmets
Originally during the rework of the Standard Factions I aimed at making communications at a distance easier by giving the PLT sections of US Army and RU Army slightly different helmets than the rest of the troops.

However, since deployment, several members approached me about that looking really odd and kinda WW2ish. I agree and thus suggest to change it back to give PLT the same helmets as the rest of the platoon.

### LINKED ISSUE #113: Standard Factions: Zeus does not have "Create zeus for this unit"

### LINKED ISSUE #114: Swap NIArms G36 for BWMod G36

### LINKED ISSUE #116: PLT Sergeant: Removal of AN/PRC-148
While updating the RU faction for v1.14.2 I realised that we could save some gear space by removing the 148 from the PLT Sergeant. Currently, the 148 is unnecessary for this role as the PLT sergeant already has access to the 117F in his backpack.

### LINKED ISSUE #117: Fireteam Colours have been reset
Just noticed that the cnto_additions update has reset all fireteam ST HUD colours to default (white).

Following colours have to be set via attributes:

A1: red
A2: yellow

B1: blue
B2: green

C1: red
C2: yellow

### PR DESCRIPTION
**Pull request by Seb105**
TFN:
-v1.14.2
-MMG: Changed MG3 to MG5 and corresponding ammo types
-GM: Fixed "assign zeus to this unit" not being present
-All Groups: Fixed radio channel presets
-Fix fireteam colours
-Gave every unit 1 epi in Uniform, or Vest if uniform was full (medic not included)
-Moved element lead LR radio to backpack
-Gave engineers more ammo (1 tracer + 1 for members, 2 tracer for leader)
-Swap platoon boonie to ECH.
-Swap DMT Marksman to "Sniper" class from "Spotter"
-Added mortar supply crate
-DMT: Removed NVG scope, and replaced main scope with one that can be used with goggles.

PMC:
-v1.14.2
-GM: Fixed "assign zeus to this unit" not being present
-All Groups: Fixed radio channel presets
-Fix fireteam colours
-Gave every unit 1 epi in Uniform, or Vest if uniform was full (medic not included)
-Moved element lead LR radio to backpack
-Added mortar supply crate
-DMT: Removed NVG scope, and replaced main scope with one that can be used with goggles.
-Gave engineers more ammo (1 tracer + 1 for members, 2 tracer for leader)

Fix #117 Fix #114 Fix #113 Fix #110 Fix #107 Fix #106 Fix #95 Fix #86 Fix #83 Fix #82 Fix #77 Fix #94

### CODE REVIEW

**Comment by JamesTheClarke** [comment]
I think issue #112 doesn't apply to this pull request. That issue was only present in US Army and Russians, right?

Or was there a similar problem with the PMC faction?

**Comment by Seb105** [comment]
Was present in TFN.

**Comment by JamesTheClarke** [comment]
Is it possible we're talking about two different issues here?

#112 was about giving all members of the PLT section the same type of helmet camos as the rest of the PLT, which for TFN was already the case as seen here: https://www.carpenoctem.co/forums/m/26081621/viewthread/33018467-changes-to-standard-factions-pure-balance-vs-true-life/post/138790057#p138790057

#82, on the other hand, was about giving the PLT Leader specifically a helmet which definitely had to be done for TFN.

What kind of helmets had to be changed? Unfortunately, I can't tell from the changelog.

**Comment by Seb105** [comment]
Oh yeah I see what you mean. Yeah only present in US Army, it's really not a big deal though.

**Comment by JamesTheClarke** [comment]
Was also present in the base version of the Russian Army preset. But I fixed it for the Russians and will do so this week for the US.

Yeah, definitely not a big deal, just wanted to check whether or not I missed something. :D

**Comment by JamesTheClarke** [comment]
I'll do a review either tonight or tomorrow. I think you also fixed #94 right? Please add it to the OP when you got some time. The linked issues help me a lot to go down the checklist when reviewing. ;)

Last question: did you manage to fix #90 as well? It's a fairly big issue for MAT teams because the scope used by TFN is really rubbish compared to the one we got for the US Army.

**Comment by Seb105** [comment]
#90 title is "MAT Scope US Army" and text is "US Army uses a different MAT launcher which in turn has a much inferior scope."

I'm fixing TFN and PMC so no, I didn't fix the US army.

And yeah #94 was fixed.

**Comment by JamesTheClarke** [comment]
My bad, I mislabelled it completely. Disregard #90 

I'm relabelling it for US Army.

**Review by baegel49 — APPROVED** [review]
Mortars for PMC and TFN don't have preset ACRE channels. Not really an issue since they're always attached to PLT anyway tho

**Pull request merged**
