### PR TITLE
Compositions version V2.1.0

### LINKED ISSUE #141: Use the "Remove ACE Medical EH" module in standard compositions
https://www.youtube.com/watch?v=ns76iVs18y0

This would allow kills to be properly credited and potentially avoid lag-induced issues by letting the game engine handle damage to enemy AI units instead of ACE doing it via an SQF script.

This module would probably have to be part of each faction composition if you want to retain ACE Medical for civilians and other sides allied to the player side, ie. if the faction is "greenfor", it has side equal to `resistance`, so any enemies would match a condition of
```sqf
(side _this) getFriend resistance < 0.6
```
For other syntax examples, see the tooltip help in the module configuration, or in the video.

### LINKED ISSUE #160: Cold war adaptations
Cold war > modern war. 

My suggestion is to add official standard faction adaptation modules that change the faction clothing to a cold war-era alternate, but preserve gear & weapon caliber (so no resupply crate jigging is necessary).

I have created an example for the Russian Army to show what I mean. As it's switching a lot of gear at once, I have included a parity check (making sure items are not lost), you are notified if there are any problems.

https://github.com/CntoDev/compositions/tree/Cold-War-Adaptations

I'd like for this issue to serve as a discussion as to whether this should be officially supported and maintained, and to discuss detials such as exactly how far down the cold war rabbit hole we want to go in terms of removing GPSes, radios etc.

### LINKED ISSUE #164: Potential Bug - DMT Callsign can't be restored
It has been noticed in a few missions since deployment of v1.14.4 that in INDFOR and OPFOR standard faction templates the DMT element sometimes remains as Alpha 2-1 even after restoring callsigns in EDEN.

It is likely that during the v1.14.4 update a mistake snuck into either the element name or the element leader naming convention.

### LINKED ISSUE #169: Make PLT Sgt loadout exactly the same as PLT Commander.
Reasons:
1. PLT Sgt often acts as JTAC/Forward Air Controller, however they cannot mark targets with red smoke UGL and so they need to ask PLT to do it for them.
2. The backpack radio won't be missed to be honest, I've never found it useful, and they'll the backpack space for the extra UGL stuff.
3. This will also fix the overfill issue for Platoon Sergeants regarding the Cold War Modules (they currently lose some smoke grenades)

### LINKED ISSUE #172: US Army overfilled units
Unit overfills occur when a container is carrying more than it allows. It will cause a unit to lose items upon spawning in. The following units/containers are overfilled in the US Army Faction

- Vehicle Commander Dagger@DAGGER uniform overfilled at 107.5 percent
- Pilot Nightbird@NIGHTBIRD uniform overfilled at 107.5 percent
- Co-Pilot Nightbird uniform overfilled at 107.5 percent
- Jet Pilot Falcon@FALCON uniform overfilled at 107.5 percent
- Game Master@GAME MASTER uniform overfilled at 107.5 percent
- Co-Game Master uniform overfilled at 107.5 percent

I have checked TFN and RUS, they are ok.

The following code will copy a list of units that are overfilled and where to the clipboard when executed from debug console:

```sqf
_overFilled = [];
{
    private _unit = _x;
    private _origLoadUniform = loadUniform _unit;   
    private _origLoadVest = loadVest _unit;   
    private _origLoadBackpack = loadBackpack _unit;  
    private _roleDescription = (_unit get3DENAttribute "description") select 0;  
    if (_origLoadUniform > 1) then      {_overFilled pushBack format ["%1 uniform overfilled at %2 percent", _roleDescription, (loadUniform _unit) * 100];};  
    if (_origLoadVest > 1) then            {_overFilled pushBack format ["%1 vest overfilled at %2 percent", _roleDescription, (loadVest _unit) * 100];};  
    if (_origLoadBackpack > 1) then    {_overFilled pushBack format ["%1 backpack overfilled at %2 percent", _roleDescription, (loadBackpack _unit) * 100];}; 
} forEach playableUnits;
copyToClipBoard str _overFilled;

```

### LINKED ISSUE #175: Insignia respawn still doesn't work
I've tested it and it definitely works on my dedicated, with/without JIP, so the issue might be with our compositions.

I've mentioned in the DMT issue, https://github.com/CntoDev/compositions/issues/164#issuecomment-801121531 , that mixing BIS insignia with my Extended Gear might be an issue, because there are now 2 different pieces of functionality racing to do the same thing:

```
        class Attribute1
        {
          property="a3aa_ee_extended_gear_insignia";
          expression="[_this, _value] call a3aa_ee_extended_gear_fnc_insignia";
          class Value
          {
              value="cnto_elem_dmt";
          };
        };
...
        class Attribute3
        {
          property="unitInsignia";
          expression="[_this,_value] call BIS_fnc_setUnitInsignia;";
          class Value
          {
              value="cnto_elem_dmt";
          };
        };
```
This was caused by somebody selecting the insignia under "Identity" and there's no easy way to remove it other than editing the `.sqe` or resetting the attribute via script.

The script is actually a good idea anyway, to remove face/voice set via the Identity tab (as has happened to at least DMT), since they are useless for player units. I'll try to come up with something and mention it in https://github.com/CntoDev/compositions/issues/162, the same piece of code should also fix this issue.

### LINKED ISSUE #176: Wrong MAT Resupply Ammo in Launcher Box and Platoon Crate
**Issue**

MAT Gunner and MAT Asst. Gunner spawn with the correct ammo types for their launcher. However, the resupply boxes and crates contain older ammo from the previous launcher model. Those rounds CAN be loaded but they are way off for ranging, up to 150m short at ranges of 700m+.

**Solution**

Place the same type of launcher ammo for the boxes and crates.

- [x] MAT Resupply Box
- [x] Platoon Resupply Crate

### LINKED ISSUE #179: Inconsistent role description of composition objects
I just noticed that ie. the US faction has a scopebox without any role description (unlike TFN). This would complicate things quite a bit if we want to automate some checks (scopebox present in a mission + scopebox marker near the box itself + scopebox on the table + ...).

Please go through all 3 main faction compositions and make sure everything placed by them has a consistent variable name (in the case of the Custom Location) or role description (for objects).

### LINKED ISSUE #181: TFN Slotting Order is Broken Again
This issue was found by @Shiny-CNTO yesterday, for some reason the Platoon Order in slotting screen is messed up again.

In order to fix it repeat these steps:

1.) select the highest element (PLT) and hit ctrl+x and ctrl+v - this automatically puts said group at the bottom of the list.
2.) repeat step one for every player group in the correct order: PLT, Alpha, Bravo, Charlie etc.

### LINKED ISSUE #185: Removal of EpiPens from Non-Medics
https://www.carpenoctem.co/forums/page/6/m/26081621/viewthread/33452198-what-do-you-like-or-hate-about-current-medical-system/post/139608992#p139608992

As per April Monthly Meeting decision the EpiPens of all non-medics will have to be removed from all three standard factions.

This change affects every soldier in the composition except medics.

### LINKED ISSUE #186: ENG Ammo & ENG Lead Coloured Smoke
https://docs.google.com/document/d/1UsldqDUJ28qpSkBMi2163irGJdkyQH5w2jSt37JHW3s/edit#

As discussed on the MMT Monthly Meeting we'll be upping their total mag counts to 10 mags (similar to regular soldiers).

In addition, we'll also be providing ENG Lead with coloured smokes to mark their own positions.

### LINKED ISSUE #187: Swap M72 Law to M136
https://docs.google.com/document/d/1UsldqDUJ28qpSkBMi2163irGJdkyQH5w2jSt37JHW3s/edit#

As per MMT Meeting after the test results of previous sessions we will be swapping the default US LAW to M136 DP.

- [x] LAT launcher
- [x] Fireteam Resupply Box
- [x] Platoon Resupply Crate

### LINKED ISSUE #188: VISCOM: Stop hiding players
One of params for spectator mode action is "hide player", we should disable this as it is messing up squad order when players enter VISCOM.

### LINKED ISSUE #189: Duplicate Composition Folders
I noticed yesterday that some compositions are placed in "double folders" / duplicated folders which causes the actual composition folder to rename itself when placed e.g. "Default Modules Coop_1". 

Bug can be observed in this commit https://github.com/CntoDev/compositions/pull/184/commits/894bfd94bc1607d968c3c9010a6478fb0db3e0d9 (line 16).

Screenshot: https://i.postimg.cc/GhV62kj5/20210531094449-1.jpg (see module overview, left panel)

This should be fixed to avoid changing composition names by accident.

Affected compositions:

- [x] TFN
- [x] Default Modules (Coop)
- [x] Default Modules (PvP)

Note: I've already fixed the issue for TFN in PR #184

### PR DESCRIPTION
**Pull request by Seb105**
### Default Modules

- ADDED new Default Module `Remove ACE Medical EH` (Coop only). This module disables ACE3 medical event handlers for enemy and neutral AI units. Allied and civilian AI units remain unaffected and players can still treat them via ACE3 medical system. This should significantly reduce situations were enemy AI can tank a lot more damage than intended. fixes #141 
- FIXED duplicate EDEN composition folder bug (Coop and PvP). fixes #189

### BLUFOR Standard Faction

- ADDED three coloured smoke grenades (2 green, 1 blue) for ENG leader. fixes #186 
- CHANGED LAT launcher from M72 Law to M136 HEDP, including Fireteam Resupply Box and Platoon Resupply Crate. fixes #187
- CHANGED default loadout for PLT Sgt role. PLT Sgt now has the same loadout as the PLT Leader, though slightly visual differences in vest and helmet. fixes #169 
- CHANGED ammo count for ENG members to be identical to regular squad members (10 mags + 1 mag loaded). fixes #186 
- CHANGED parameter for VISCOM to avoid DUI bug regarding squad order. fixes #188
- REMOVED epi-pens for all non-medic roles. fixes #185 
- FIXED inconsistent variable naming convention. fixes #179 
- FIXED wrong MAT ammo in resupply crates. fixes #176 
- FIXED overfilled unit loadouts. fixes #172 
- FIXED unit insignia not respawning. fixes #175 

### INDFOR Standard Factions

- ADDED three coloured smoke grenades (2 green, 1 blue) for ENG leader. fixes #186 
- CHANGED LAT launcher from M72 Law to M136 HEDP, including Fireteam Resupply Box and Platoon Resupply Crate. fixes #187
- CHANGED default loadout for PLT Sgt role. PLT Sgt now has the same loadout as the PLT Leader. fixes #169 
- CHANGED ammo count for ENG members to be identical to regular squad members (10 mags + 1 mag loaded). fixes #186
- CHANGED parameter for VISCOM to avoid DUI bug regarding squad order. fixes #188
- REMOVED epi-pens for all non-medic roles. fixes #185 
- FIXED bug regarding callsign restoration of DMT element. fixes #164 
- FIXED inconsistent variable naming convention. fixes #179 
- FIXED faulty element slotting order. fixes #181 
- FIXED unit insignia not respawning. fixes #175 
- FIXED duplicate EDEN composition folder bug. fixes #189 

### OPFOR Standard Factions

- ADDED three coloured smoke grenades (2 green, 1 blue) for ENG leader. fixes #186 
- CHANGED default loadout for PLT Sgt role. PLT Sgt now has the same loadout as the PLT Leader, though slightly visual differences in vest and helmet. fixes #169 
- CHANGED ammo count for ENG members to be identical to regular squad members (10 mags + 1 mag loaded). fixes #186
- CHANGED parameter for VISCOM to avoid DUI bug regarding squad order. fixes #188
- REMOVED epi-pens for all non-medic roles. fixes #185 
- FIXED bug regarding callsign restoration of DMT element. fixes #164 
- FIXED inconsistent variable naming convention. fixes #179
- FIXED unit insignia not respawning. fixes #175  

### Standard Faction Adaptation Modules

- ADDED three new Cold War adaptations modules (BLUFOR, INDFOR & OPFOR). These adaptation modules automatically change the loadouts for each standard faction to gear from the late 70ies / early 80ies. fixes #160

### Review Process

Assigned for PR review are Mission Making Manager, R&D and the SSgts. Min. 2 green-light reviews needed for merger into Master. Please only green-light if you spot-checked every category above.

Once reviewed and merged the composition update will be released on GitHub and on our Steam Workshop.

### CODE REVIEW

**Comment by Seb105** [comment]
Note: #141 implementation is untested and needs proper doing in MP

**Comment by freghar** [comment]
> Note: #141 implementation is untested and needs proper doing in MP

Any chance of that happening soon? .. Thanks.

**Comment by freghar** [comment]
Seems to work for me just fine in dedicated MP - allied AI soldiers do have medical, players do, enemies don't.

**Comment by JamesTheClarke** [comment]
I've updated the Changelog in the OP to make it more expansive and easy to read in one location what exactly was changed.

Also I tested #164 for TFN and RU and noticed that the fix was only deployed for TFN. @Seb105 could you implement the same fix for RU as well? Please get the latest version of PF #184 first because I made further changes to RU (see https://github.com/CntoDev/compositions/pull/184/commits/7db23a057a0807968bcb1dfb0cec24baa40d53f6 )

**Comment by JamesTheClarke** [comment]
I'm done with my commits to this PR. As soon as issue #164 is also fixed for RU Army we can start the review process and subsequent deployment.

**Comment by Seb105** [comment]
I recall it not being a problem with the Russian faction. Is it definitely broken?

**Comment by JamesTheClarke** [comment]
> I recall it not being a problem with the Russian faction. Is it definitely broken?

I tested it in local MP before I made the issue report, that's why I tagged both factions. Feel free to double-check by placing down the OPFOR faction and the Default Coop Modules, then host it in local MP.

**Comment by JamesTheClarke** [comment]
Had a quick chat with @Seb105 and he's also very busy atm and won't be able to add the RU Army DMT fix before the weekend. Same goes for me and @freghar .

Freghar and I agreed that it's best to push this PR for review and hopefully deployment asap. I've adapted the OP the reflect that DMT fix for RU Army is still outstanding.

**Comment by freghar** [comment]
Since the OP mentions

> Please only green-light if you spot-checked every category above.

I won't green-light this as I haven't tested everything, but I did test insignia respawn (works) and ACE Medical EH (doesn't work).

The problem is that I haven't tried the medical EH **with a headless client connected**, I didn't think it would be relevant, but it turns out it is, as HC is just like another player, but friendly to everybody, rendering the module useless.

The fix is pretty straightfoward (tested on dedicated with a HC):
```sqf
private _players = playableUnits + allPlayers - units sideLogic - [objNull];
if (isPlayer _this || _this in _players) exitWith { false };
(_players findIf { side _x getFriend side _this >= 0.6 }) isEqualTo -1;
```

**Comment by JamesTheClarke** [comment]
Since I contributed to this PR I will only be reviewing commits by @Seb105

- [ ] ADDED new Default Module Remove ACE Medical EH (Coop only). #141
- [ ] ADDED three new Cold War adaptations modules. #160
- [ ] CHANGED parameter for VISCOM to avoid DUI bug regarding squad order. #188
- [ ] FIXED bug regarding callsign restoration of DMT element. #164
- [ ] FIXED inconsistent variable naming convention. #179
- [ ] FIXED faulty element slotting order. #181

**Review by Shiny-CNTO — APPROVED** [review]
Tested it today and I haven't found any issues. Approved in my book.

**Review by JamesTheClarke — APPROVED** [review]
This is only a partial PR review. See: https://github.com/CntoDev/compositions/pull/184#issuecomment-855308069

**Review by baegel49 — APPROVED** [review]
I've had a look and everything is there as far as I can tell, ty

**Pull request merged**
