### PR TITLE
Add EZFaction module

### PR DESCRIPTION
**Pull request by Seb105**
Module for following: https://gist.github.com/Seb105/4e3b653b83a2f723884e73b92310bf2e

### CODE REVIEW

**Comment by Shiny-CNTO** [comment]
What does ezfaction module do ? Google comes up with nothing except your profile.

**Comment by Seb105** [comment]
It's this: https://www.carpenoctem.co/forums/m/26081621/viewthread/33564591-custom-faction-tool-to-skip-review-process

**Review by JamesTheClarke — APPROVED** [review]

**Review by redteddy — APPROVED** [review]

**Comment by Shiny-CNTO** [comment]
Ok cool. Did not know that this was the name! Approved!

**Review by Shiny-CNTO — APPROVED** [review]

**Comment by Seb105** [comment]
Yeah I thought I'd give it a catchy name.

Note it won't work properly with the Russian faction until https://github.com/CntoDev/compositions/issues/199 is fixed.

**Review by Shadisica — APPROVED** [review]

**Pull request merged**
