### PR TITLE
Issue 134/seb

### LINKED ISSUE #134: 3 year old standard factions in Misc-Compositions

### PR DESCRIPTION
**Pull request by Seb105**
close #134

### CODE REVIEW

**Comment by Seb105** [comment]
Not sure why 4 commits ended up here but they dont change anything

**Comment by freghar** [comment]
Changes look good, just make to Squash Merge this, not Rebase Merge.

**Review by JamesTheClarke — APPROVED** [review]

**Comment by JamesTheClarke** [comment]
@freghar why squash merge instead of rebase merge? by default squash merge and merge commit have been disabled on this repo.

**Comment by freghar** [comment]
There are 3 ways to merge:

1. Using a merge commit to join two histories of commits
1. Using Rebase Merge, which just "takes" all the commits from another branch and puts them, one by one, on the destination
1. Using Squash Merge, which works like Rebase Merge, but squashes all commits into one, good for "hiding" extra commits if the PR author isn't proficient enough with git to get rid of them so a clean Rebase Merge can be done

**Comment by milivojm** [comment]
Why merge directly into master?

**Comment by JamesTheClarke** [comment]
@freghar I've enabled Squash and merge for this repository.

Once @baegel49 has reviewed this change he can use squash and merge for this commit to remove the outdated files.

**Review by baegel49 — APPROVED** [review]

**Pull request merged**
