### PR TITLE
Cold war adaptations

### PR DESCRIPTION
**Pull request by Seb105**
Adds standard faction adaptation modules that convert each of our main faction into cold war, 1980s-ish alternatives.
* Removes IR strobes
* Swaps Vectors for boring old binocs.
* Removes GPS
* Removes radios if a standard squad member i.e not a leader, special squad, or medic.
* Pallete swap faction with coldwar stuff
* Swap ammotypes where appropriate
* Swap ammotypes in the ammoboxes too. Figuring out how to do this made me want to commit die.

Future expandability:
* Parity checks - checks that find & replace changes made are actually valid, and warns if they are not (obviously I have fixed any issues so there are no parity warnings in this submission, but trying doing something dumb yourself and see the warnings it throws)
* Overfill warnings (see end note).

RUS, TFN Plt. Sgts vests now get "overfilled" by 5%, meaning they are carrying 5% more than the vest technically allows. 
This isn't a problem as they won't lose items, they just won't be able to pick things up into their vest until they've lightened the load.
I do not consider this a problem as it turns out some units are already overfilled, so if other people can do it I can too 😎

### CODE REVIEW

**Comment by baegel49** [comment]
This is really great and will see a lot of use from my side, so thank you Seb.

Some things to consider:
- US faction still has PMAGs equipped, which look very strange in an M16A2 imo. Not a deal breaker, but if they could be swapped to metal STANAGs it be cool
- I would use different helmets for TFN. Currently the same as the US, very 80s, very evocative, but too similar IMO. I suggest either the M97 Olive or if its not camo enough then the PASGT (Olive)

**Comment by Seb105** [comment]
M97 is actually entirely european, but yeah it does look similar.

**Comment by baegel49** [comment]
I lowkey love the non-camo look of the M97 Olive, makes it look like TFN has an interesting history, maybe a unit that was thrown together quickly to act as a european SF against the soviet threat but without having figured out their camo patterns yet etc.

**Comment by Seb105** [comment]
I won't be able to make changes until like 6 tonight. It'd be a good test of the maintainability if you swapped it.

**Comment by baegel49** [comment]
Will do

**Comment by Seb105** [comment]
_new_inventory_item is the lookup table for items including magazines in guns, inventories and boxes.

**Comment by baegel49** [comment]
I can switch the mag in the gun for US and the helmets for TFN no problem, but I have no idea how to switch mags in a vest

**Comment by Seb105** [comment]
The same function, `_new_inventory_item` changes items in all supply boxes, magazines in guns, and items in unit inventory. See TFN/RUS for it in use.

**Comment by baegel49** [comment]
oh so just add another `case "rhs_bla_bla": { "rhs_stanag_blabla" };`

**Comment by Seb105** [comment]
Yeah.

**Comment by baegel49** [comment]
Not an issue at all then

**Comment by baegel49** [comment]
Changes are done but I have no idea how to upload them to a pull request

**Comment by Seb105** [comment]
https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-branches

**Comment by JamesTheClarke** [comment]
@baegel49 there's also a newbie-friendly guide Flo wrote (I added some infos later) using the GitHub Desktop App: https://www.carpenoctem.co/forums/m/26081621/viewthread/33175426-mission-making-github-manual

I pretty much commit and pull request with that method exclusively.

**Comment by baegel49** [comment]
lets just hope i didnt break anything :D

**Comment by baegel49** [comment]
Actually one issue is that DMT for TFN isnt affected at all by the module

**Comment by Seb105** [comment]
I can fix later today, or you can fix it now as the functionality is there.

If you do fix it, can you delete these lines of codes while you're at it:
```
private _replace_container_items = { 

};
```

Function I ended up not needing to make and now it's just there to be confusing.

```_new_inventory_item``` should also have a better name I guess as it's not currently explicit that it does containers, unit loadouts and weapon magazines at the same time.

**Comment by Seb105** [comment]
This is ready for a proper review

**Comment by Seb105** [comment]
Issues discovered during test:
1. Platoon has no 343. Guess my check script isn't perfect
2. Overfilled uniforms DO seem to delete uniforms. This will require shifting some gear around to make room in the vests for ENG & PLT SGT, requiring a modification of the base faction. Luckily it's fine for most units.

**Comment by Shiny-CNTO** [comment]
3. MMG vest is modern and has armor value of 4 instead of 3.

**Comment by Seb105** [comment]
That's just the PASGT. Can't fix unfortunately.

**Comment by JamesTheClarke** [comment]
If we fix #176 I assume the swapping of the ammo type to cold-war in the launcher box and platoon crate will no longer work, correct?

**Comment by Seb105** [comment]
It'll still work, it's a find and replace of the original items in the box and MAT stuff isn't touched by the script. 

Any changes you make the main faction will be reflected in adaptations, and you'll be warned if there are any issues when placing the adaptation modules

**Review by JamesTheClarke — CHANGES_REQUESTED** [review]
- US MMG Gunner still had a modern vest.
- TFN PLT Sergeant throws warning about overfilled gear being lost.

remaining discovered issues seem to be fixed from my spot checks.

**Comment by Seb105** [comment]
Will https://github.com/CntoDev/compositions/issues/169 be implemented? If so won't fix 2 and 3.

**Comment by JamesTheClarke** [comment]
> Will #169 be implemented? If so won't fix 2 and 3.

Yes, currently working on the latest composition update. I assumed these two issues were connected to the expectation of a fix of #169 , mentioned them for completion sake.

**Review by JamesTheClarke — DISMISSED** [review]
- US MMG Vest was fixed during 2nd spot check.
- As discussed overload issues were not fixed since they will be addressed by a different issue fix.
- spot checked randomly several other roles and didn't run into anything noteworthy.

**Comment by Seb105** [comment]
@baegel49 Final review & merge pls

**Comment by Seb105** [comment]
Wait no don't, RHS just added a bunch of new Russian stuff I want to use.

**Comment by baegel49** [comment]
Ok well ill do a final test once you are 100% everything is done

**Comment by Seb105** [comment]
@baegel49 good to go.

**Review by baegel49 — APPROVED** [review]
Did spot checks on all three factions, if anything crops up I'm sure our players will let Seb know.

**Comment by freghar** [comment]
I copied the code to my notepad and did some post-processing so I don't have to launch Arma, just a few minor things, nothing critical. I haven't gone line-by-line, just skimmed the code.

```sqf
private _itemsArr = _containerArr select 1;
{
    private _itemArr = _x;
    private _item = _itemArr select 0;
    if (_item == "ACE_IR_Strobe_Item") then {
        _itemsArr set [_forEachIndex, "deleteMe"];
    };
} forEach _itemsArr;
_containerArr set [1, _itemsArr - ["deleteMe"]];
```
and its multiple variants could be probably simplified,
```sqf
private _itemsArr = _containerArr select 1;
_itemsArr = _itemsArr select {
    private _item = _itemArr select 0;
    _item != "ACE_IR_Strobe_Item";   // or !(_item in ["..."])
};
_containerArr set [1, _itemsArr];
```

Then,
```sqf
private _expectedGear = +_gear;
```
no clue why the deep array copy is needed, neither of them is modified in the following code.

**Comment by Seb105** [comment]
Not worth fixing now, I will keep it in mind if I come back to this.

**Pull request merged**
