### PR TITLE
Bundeswehr Custom Faction

### PR DESCRIPTION
**Pull request by baegel49**
This adds the German Army (Bundeswehr) as a custom faction which I will maintain over time. It also has a 90s version with G3s instead of G36s and a tropentarn (desert camo) adaptation module.

### CODE REVIEW

**Comment by JamesTheClarke** [comment]
With the big upcoming updates to the main composition, cba file and the mod repositories I won't have time to review this soon.

Custom factions don't need approval from SSgts to be added to the repo. As long as another Mission Maker (ideally somebody who's got experience with Custom Factions) reviews it the faction can be merged.

**Comment by baegel49** [comment]
I will need to update this to reflect telestation changes etc. 

Will also add a version of Seb's Cold War adaption module to this.

**Comment by JamesTheClarke** [comment]
> I will need to update this to reflect telestation changes etc.
> 
> Will also add a version of Seb's Cold War adaption module to this.

Please make sure the composition also will include the INDFOR changes from https://github.com/CntoDev/compositions/pull/184

**Comment by JamesTheClarke** [comment]
Pull request closed due to upcoming removal of BW mod.

**Pull request closed without merging**
