### PR TITLE
V3.0.2

### LINKED ISSUE #162: Improve Repo Documentation
Goals Overview:

- [x] shorten ReadMe file to the bare minimum (introduction, links to wiki, license agreement)
- [x] add full license agreement
- [ ] expand wiki with pages for different topics (e.g. how to update compositions, how to maintain repository, how to report issues and deploy releases etc.)

Benefits:

- more formatting options
- wiki updates can be done independent from commits and PRs

### LINKED ISSUE #191: Add the "Locality transfer (to HC)" module to Default Modules (Coop)
Place down the A3AA --> Locality transfer module and leave the default settings in it, then save it to the Coop module composition.

This is the new transfer implementation that should be more compatible and predictable, see https://www.carpenoctem.co/forums/m/26081621/viewthread/33531535-how-to-test-new-better-headless-client-logic .

This change must be done at the same time as https://github.com/CntoDev/cba-settings-lock/issues/46 .

### PR DESCRIPTION
**Pull request by JamesTheClarke**
### Default Modules

- ADDED A3AA Locality Transfer Modules - fixes #191 

### BLUFOR

- CHANGED composition version from v3.0.1 to v3.0.2

### INDFOR

- CHANGED composition version from v3.0.1 to v3.0.2

### OPFOR

- CHANGED composition version from v3.0.1 to v3.0.2

### GitHub Repo Structure

- CHANGED ReadMe file - fixes #162

- ADDED License Agreement file - fixes #162

### CODE REVIEW

**Comment by freghar** [comment]
For the record, this needs to go out at the same time https://github.com/CntoDev/cba-settings-lock/pull/56 is implemented, and older composition version must not be allowed on official missions, otherwise the mission will run without any headless transfer.

**Comment by JamesTheClarke** [comment]
Review by @Shadisica is mandatory for merger, reviews by @Shiny-CNTO and @redteddy are optional since there are no balance changes in this PR.

**Review by redteddy — APPROVED** [review]

**Review by redteddy — APPROVED** [review]

**Review by Shiny-CNTO — APPROVED** [review]
Looks good!

**Review by Shadisica — APPROVED** [review]
No issues from my end!

**Pull request merged**
