### PR TITLE
v1.14.4

### LINKED ISSUE #84: Create a HAT team for standard factions
US forces - 2 man Javelin team
TFN - 2 man Javelin team
Russians -  ?

### LINKED ISSUE #111: Messy Uniform & Vest Gear
A lot of our uniform and vest gear has changed over time and thus some historical weird stuff snuck in over time such as one tourniquet being in the uniform and the other in the vest.

With issue #107 and #95 coming up in the next version I think it's a good time to properly order items again in the uniform.

I propose the following order I also employed for my vietnam faction:

- 4x Bandage (Basic)
- 6x Basic Field Dressing (QuikClot)
- 2x Tourniquet (CAT)
- 1x Morphine
- 1x Epinephrene
- Rest of the uniform items (differs per role)

This will require the updating contributors to completely remove all uniform items except the basic bandage and the quikclots and then refill them in the correct order.

### LINKED ISSUE #140: Convert scopebox to function-based
Scopebox going forward will be called via cnto-additions function, All scopeboxes will need updating to simply be the following:

`this call cnto_fnc_scopebox`

Rather than the actual scopebox code itself. Only to be done when Zeus_Enhanced is in the modpack and the version of Arma-additions containing the function is on the repo..

### LINKED ISSUE #142: Add New Element Insignias to Respective Units
With the updated cnto-assets we have now element insignia patches made by Hateboarder available for all units.

https://github.com/CntoDev/cnto-assets/pull/12

### LINKED ISSUE #143: Add HMG team to US, TFN, RU factions
Maybe won't be used much, but its nice for MMT to have the option to include an HMG team. This would function similar to mortar team as a two man team with backpacks, ~~with extra HMG backpacks in the mortar resupply~~. Its main targets would include lightly armoured vehicles.

**US HMG team:**
- M2 Gun Bag
- M3 minitripod Bag

**RU HMG team:**
- KORD gun bag
- KORD 6T7 Tripod Bag

**TFN HMG team:**
- Dismantled M2 HMG .50 [AAF]
- Folded Tripod M2 HMG .50 [AAF]

**EDIT:** 
Extra HMG backpacks should have their own resupply container to keep the mortar crate from being too heavy and still portable. In addition, a "high variant" of the HMG tripods should be available in the HMG resupply crate to allow HMG the option of choosing one over the other. This would mean that the usual "box guard" script should not apply, to allow HMG to make their choice while at spawn.

### LINKED ISSUE #144: Uniform Naming Convention of Role Descriptions
During the current update process I noticed some minor inconsistencies in the role description naming convention such as:

- some roles were not capitalised while the vast majority of them are capitalised
- the term Assistant is abbreviated with ass. assist. and asst. - using the existing Arma internal abbreviation of asst. makes the most sense

### LINKED ISSUE #145: All TFN camo modules are broken
They do not contain an "execute code (3den)" module at all.

### PR DESCRIPTION
**Pull request by JamesTheClarke**
PR Changelog:

- added new element insignia patches to all relevant elements: fixes #142
- added new ZEN scope box: fixes #140
- added HAT element: fixes #84
- added HMG element: fixes #143
- added supply crates for the new elements
- assigned channels 9, 1 to HMG/HAT element leaders
- assigned channels 9 to element HMG/HAT members
- assigned role uniform description naming convention: fixes #144
- redistributed existing TFN uniform & vest gear: fixes #111
- changed RU supply crates from Middle Eastern to Greek (visually closer to Russian)
- changed TFN supply crates from Greek to English (visually closer to TFN)
- enabled dynamic simulation for all resupply crates
- removed "disable LAMBS AI" on all units to avoid mod dependency
- removed the changelog within version comment module since it was cumbersome to read and maintain - we already have version control via GitHub
- created a "depreciated" folder and moved unused Viscom and Scopebox compositions from reference to depreciated.
- fixed TFN infantry camo modules: fixes #145

**Minimum two reviews before merger with Master due to the amount of changes! Please only greenlight a review if you have spot-checked all three Standard Factions!**

If I haven't tagged you for review but you still wanna contribute feel free to drop a review!

### CODE REVIEW

**Comment by baegel49** [comment]
1. HAT gunner weighs 55kg and can barely move. Suggest moving the extra AT missile to the Asst. by adding a carry all backpack and reducing other gear in his backpack. Leave the carry all backpack for the gunner but leave it empty so the Asst. can add a missile through the backpack.
2. Laptops from Viscom and scopebox do not have their simulation disabled.

**Review by Seb105 — COMMENTED** [review]
Will reopen https://github.com/CntoDev/compositions/issues/102 as it stands.

**Comment by JamesTheClarke** [comment]
@baegel49 I've updated all three Standard Factions and fixed the HAT Gunner weight issues, double checked scopeboxes and viscom simulations and in the same move enabled dynamic simulation for all resupply boxes to further lower potential performance impacts.

**Comment by JamesTheClarke** [comment]
> Will reopen #102 as it stands.

I'm a bit confused as to why. I only replaced the infantry camo modules in this PR. I did not update the vehicle camo files at all, those should still be the same as it was last commit by @milivojm.

@milivojm could you take a look at the vehicle camo module? This PR attempts to fix #145

**Comment by Seb105** [comment]
> 
> 
> > Will reopen #102 as it stands.
> 
> I'm a bit confused as to why. I only replaced the infantry camo modules in this PR. I did not update the vehicle camo files at all, those should still be the same as it was last commit by @milivojm.
> 
> @milivojm could you take a look at the vehicle camo module? This PR attempts to fix #145

Vehicle/Infantry camo are the **SAME COMPOSITION** which contains **TWO MODULES** - vehicle and infantry camo.
Both are contained within a **single .sqm** composition file.

By reverting back to August 2020 you have deleted Highway's fixes to vehicle camos, which were done in the execute code module and therefore modify the .sqm as it's a single file, not multiple files per module. If you reverted TFN

**Comment by JamesTheClarke** [comment]
> > > Will reopen #102 as it stands.
> > 
> > 
> > I'm a bit confused as to why. I only replaced the infantry camo modules in this PR. I did not update the vehicle camo files at all, those should still be the same as it was last commit by @milivojm.
> > @milivojm could you take a look at the vehicle camo module? This PR attempts to fix #145
> 
> Vehicle/Infantry camo are the **SAME COMPOSITION** which contains **TWO MODULES** - vehicle and infantry camo.
> Both are contained within a **single .sqm** composition file.
> 
> By reverting back to August 2020 you have deleted Highway's fixes to vehicle camos, which were done in the execute code module and therefore modify the .sqm as it's a single file, not multiple files per module. If you reverted TFN

Thank you for the more detailed explanation, now I understand the issue. I always thought they were separate compositions since there is a separate TFN vehicle module folder: https://github.com/CntoDev/compositions/tree/master/reference/Task%2520Force%2520Noctem%2520Vehicles
I assume that folder is depreciated? Or what is that composition used for?

I'll recommit a fix that hopefully addresses both #102 and #145 .

**Comment by Seb105** [comment]
That composition is TFN's 'standard' suite of vehicles that the vehicle camo module actually applies to. It's not _used_ super often, but isn't deprecated.

**Comment by JamesTheClarke** [comment]
I used to test the vehicle camo module by spawning relevant vics individually in the editor :D forgot we had a composition for them all.

The latest commit includes @milivojm 's fix and the deleted infantry camo modules. I've tested the vic camo module with the vehicle composition and noticed that except for the snow camo all other camos don't work for the Mora IFV. But that's not a game-breaker, just a thing to be aware of.

**Review by baegel49 — DISMISSED** [review]
Looks good to me. All the things I found were fixed by Clarke's quick hot fix.

**Review by Shiny-CNTO — CHANGES_REQUESTED** [review]
The scopebox is floating 1m above the table and the laptops are sunking into the table when you just place it. In v14.3 they were both working fine. This is for TFN 1.14.4

**Comment by JamesTheClarke** [comment]
> The scopebox is floating 1m above the table and the laptops are sunking into the table when you just place it. In v14.3 they were both working fine. This is for TFN 1.14.4

This is something I can't fully influence and can differ from client to client. For example, in v1.14.3 all the boxes and laptops floated for me 10m in the air for all three Standard Factions. In v1.14.4 it only shows up in US Army but not RU or TFN. I assume this is directly related to this BI Terrain Level issue: https://community.bistudio.com/wiki/Eden_Editor:_Custom_Composition

> Terrain Level: composition will be snapped to the surface underneath. Please note that objects which are placed on another objects may no longer be positioned precisely.


In any case this won't be a deal breaker for the release. Did you spot-check the rest of the changelog as well? If not please post another review when you checked the full changelog.

**Comment by JamesTheClarke** [comment]
The latest commit fixes some issues with the HMG team loadouts and attempts to fix the floating scope box for TFN and RU:

**Changelog**

TFN, US & RU:
- removed 81mm range table from HMG Gunner and Asst. Gunner
- removed maptools from HMG Gunner
- removed green and blue smoke grenades from HMG Gunner
- changed HMG resupply crate to plastic case (medium) to visually distinct it from the Mortar resupply crate

TFN & US:
- fixed floating scopebox (not yet tested with more clients)

**Comment by baegel49** [comment]
Can confirm its no longer floating on my end. Did a quick spot check again and didnt find anything amiss.

**Review by Shiny-CNTO — APPROVED** [review]
Floating is fixed and I love the new change with the different crate for HMG!
I no longer see issues and approve of this new version!

**Review by baegel49 — APPROVED** [review]

**Pull request merged**
